import { FormEvent, useEffect, useState, type ReactNode } from "react";
import { Link } from "react-router-dom";

type Service = { icon: string; title: string; description: string; items?: string[] };
const icons = ["Wrench", "Zap", "Monitor", "Fuel", "Cpu"];
const emptyService = (): Service => ({ icon: "Cpu", title: "", description: "", items: [] });

const Field = ({ label, children }: { label: string; children: ReactNode }) => (
  <label className="block space-y-2"><span className="text-xs tracking-widest uppercase text-primary">{label}</span>{children}</label>
);

export default function Admin() {
  const [authenticated, setAuthenticated] = useState(false);
  const [services, setServices] = useState<Service[]>([]);
  const [login, setLogin] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState("");
  const load = () => fetch("/api/services").then((r) => r.json()).then(setServices);
  useEffect(() => { fetch("/api/admin/session").then((r) => r.json()).then((data) => { setAuthenticated(data.authenticated); if (data.authenticated) load(); }); }, []);
  const submitLogin = async (event: FormEvent) => { event.preventDefault(); const r = await fetch("/api/admin/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ login, password }) }); if (r.ok) { setAuthenticated(true); setPassword(""); load(); } else setMessage("Nieprawidłowy login lub hasło."); };
  const update = (index: number, value: Service) => setServices(services.map((item, i) => i === index ? value : item));
  const save = async () => { const r = await fetch("/api/admin/services", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(services) }); setMessage(r.ok ? "Zmiany zapisane." : "Nie udało się zapisać zmian."); };
  if (!authenticated) return <main className="min-h-screen bg-background text-foreground grid place-items-center p-6"><form onSubmit={submitLogin} className="w-full max-w-md border gold-border bg-card p-8 md:p-10 space-y-5 card-shadow"><p className="text-primary text-xs tracking-[.3em] uppercase">Panel administracyjny</p><h1 className="font-heading text-4xl">Zaloguj się</h1><input required value={login} onChange={(e) => setLogin(e.target.value)} placeholder="Login" className="w-full p-3 bg-background border gold-border" /><input required type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Hasło" className="w-full p-3 bg-background border gold-border" /><button className="w-full p-3 bg-gradient-gold text-primary-foreground font-semibold">Zaloguj</button><p className="text-red-400 text-sm">{message}</p></form></main>;
  return <main className="min-h-screen bg-background text-foreground p-6 md:p-12"><div className="max-w-5xl mx-auto"><header className="mb-10"><p className="text-primary text-xs tracking-[.3em] uppercase mb-3">Panel administracyjny</p><h1 className="font-heading text-4xl md:text-5xl">Zarządzanie stroną</h1></header><nav className="flex gap-2 border-b gold-border mb-8"><Link to="/admin" className="px-6 py-3 bg-card border-t border-x gold-border text-primary">Usługi</Link><Link to="/admin/realizacje" className="px-6 py-3 text-muted-foreground hover:text-primary">Realizacje</Link></nav><div className="space-y-6">{services.map((service, index) => <section key={index} className="border gold-border bg-card p-6 md:p-8 space-y-5"><div className="flex items-center justify-between"><span className="text-primary text-xs tracking-widest uppercase">Kafelek {index + 1}</span><button onClick={() => setServices(services.filter((_, i) => i !== index))} className="text-sm text-red-400">Usuń</button></div><Field label="Tytuł"><input value={service.title} onChange={(e) => update(index, { ...service, title: e.target.value })} className="w-full p-3 bg-background border gold-border" /></Field><Field label="Ikona"><select value={service.icon} onChange={(e) => update(index, { ...service, icon: e.target.value })} className="p-3 bg-background border gold-border">{icons.map((icon) => <option key={icon}>{icon}</option>)}</select></Field><Field label="Opis"><textarea value={service.description} onChange={(e) => update(index, { ...service, description: e.target.value })} className="w-full p-3 bg-background border gold-border min-h-28" /></Field><Field label="Punkty listy"><textarea value={(service.items || []).join("\n")} onChange={(e) => update(index, { ...service, items: e.target.value.split("\n").filter(Boolean) })} placeholder="Jeden punkt w każdym wierszu" className="w-full p-3 bg-background border gold-border min-h-24" /></Field></section>)}</div><div className="flex gap-4 mt-8"><button onClick={() => setServices([...services, emptyService()])} className="px-5 py-3 border gold-border">+ Dodaj kafelek</button><button onClick={save} className="px-6 py-3 bg-gradient-gold text-primary-foreground font-semibold">Zapisz zmiany</button></div><p className="mt-4 text-primary">{message}</p></div></main>;
}
