import { useEffect, useState, type ReactNode } from "react";
import { ChevronDown, Cpu, Fuel, Monitor, Wrench, Zap, Cog, Phone, type LucideIcon } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import CallButton from "@/components/CallButton";
type Service={icon:string;title:string;description:string;fullDescription?:string;faq?:string;items?:string[]};
const icons:Record<string,LucideIcon>={Cpu,Fuel,Monitor,Wrench,Zap,Cog};
const fallback:Service[]=[{icon:"Wrench",title:"Mechanika",description:"Kompleksowe naprawy mechaniczne."},{icon:"Zap",title:"Elektryka",description:"Diagnostyka instalacji i modułów."}];
function Faq({text}:{text:string}){const [open,setOpen]=useState<number>();const rows=text.split("\n").filter(Boolean).map(row=>{const [question,...answer]=row.split("|");return {question,answer:answer.join("|").trim()};});return <div className="mt-6 pt-6 border-t gold-border"><h3 className="font-heading text-xl text-primary mb-3">FAQ</h3>{rows.map((row,i)=><div key={i} className="border-b border-primary/20"><button onClick={()=>setOpen(open===i?undefined:i)} className="w-full flex justify-between gap-4 py-4 text-left text-foreground"><span>{row.question}</span><ChevronDown className={`w-5 h-5 text-primary transition-transform ${open===i?"rotate-180":""}`}/></button>{open===i&&<p className="pb-4 text-muted-foreground leading-relaxed">{row.answer}</p>}</div>)}</div>}
export default function ServicesPage(){const [services,setServices]=useState< Service[]>(fallback);const [expanded,setExpanded]=useState<number>();useEffect(()=>{fetch("/api/services").then(r=>r.json()).then(data=>data.length&&setServices(data)).catch(()=>undefined)},[]);return <><Navbar/><main className="min-h-screen bg-background text-foreground pt-32 pb-20"><header className="max-w-4xl mx-auto px-4 text-center mb-16"><p className="text-primary text-xs tracking-[.3em] uppercase mb-4">Profesjonalny serwis</p><h1 className="text-4xl md:text-6xl font-heading">Zakres <span className="text-gradient-gold">usług</span></h1></header><div className="max-w-5xl mx-auto px-4 space-y-5">{services.map((service,index)=>{const Icon=icons[service.icon]||Cpu;const isOpen=expanded===index;return <article key={`${service.title}-${index}`} className="border gold-border bg-card"><button onClick={()=>setExpanded(isOpen?undefined:index)} className="w-full flex items-center gap-5 p-7 md:p-9 text-left"><Icon className="w-9 h-9 shrink-0 text-primary"/><span className="flex-1 font-heading text-2xl md:text-3xl">{service.title}</span><ChevronDown className={`w-6 h-6 text-primary transition-transform ${isOpen?"rotate-180":""}`}/></button>{isOpen&&<div className="px-7 pb-8 md:px-9"><p className="text-muted-foreground leading-relaxed">{service.description}</p>{service.items&&<ul className="mt-5 space-y-2 text-muted-foreground">{service.items.map(item=><li key={item}>• {item}</li>)}</ul>}{service.fullDescription&&<div className="mt-6 pt-6 border-t gold-border whitespace-pre-line leading-8 text-muted-foreground">{service.fullDescription}</div>}{service.faq&&<Faq text={service.faq}/>}</div>}</article>})}</div><div className="text-center mt-14"><CallButton className="inline-flex items-center gap-2 px-8 py-4 bg-gradient-gold text-primary-foreground font-semibold uppercase tracking-wider"><Phone className="w-5 h-5"/>Zadzwoń do nas</CallButton></div></main><Footer/></>}
